### ISSUE TITLE
Slower if the ROI Manager is not empty 

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/ijp-LaRoMe#10]
fom [forum post](https://forum.image.sc/t/clij-label-map-to-roi-fast-version/51356/29?u=romainguiet) "the ROI Manager window is open and already contains many ROIs it takes 5-10 times longer"

**Comment by lacan** [comment]
The latest version should fix this. See https://github.com/BIOP/ijp-LaRoMe/pull/17 and https://github.com/BIOP/ijp-LaRoMe/pull/16
