### ISSUE TITLE
Time-lapse case slow, Batch mode issue

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/ijp-LaRoMe#11]
From [forum post](https://forum.image.sc/t/clij-label-map-to-roi-fast-version/51356/29?u=romainguiet), "Applying the function on (time-lapse) stacks somehow is much slower (~100 times), because it swaps between the slices/frames. Hiding the image in batch mode results in zero ROIs."

**Comment by lacan** [comment]
Fixed with latest commits see https://github.com/BIOP/ijp-LaRoMe/pull/17 and https://github.com/BIOP/ijp-LaRoMe/pull/16
