### ISSUE TITLE
batch conversion

### ISSUE THREAD

**Issue by its-jd** [BIOP/ijp-LaRoMe#3]
Hi, thanks for the very nice and easy to use plugin!
I am using this Plugin to create a label image from ROIs. Is there any way that I can do batch operation on many images and ROIs within one folder?

**Comment by romainGuiet** [comment]
Hi,
>thanks for the very nice and easy to use plugin!

I'm happy it can be useful for others!

>I am using this Plugin to create a label image from ROIs. Is there any way that I can do batch operation on many images and ROIs within one folder?

I'm pretty sure we can do something about it! Maybe it will be useful for others and we can discuss it on the image.sc forum?
You can open a topic there and tag me @romainGuiet

**Comment by romainGuiet** [comment]
cf [topic on forum](https://forum.image.sc/t/batch-operation-for-generating-label-image-from-rois-and-vice-versa/48171/2)
